import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import ModelProvider from "@/providers/modal-provider";
import { Toaster as SonnarToaster } from "@/components/ui/sonner";

// const inter = Inter({ subsets: ["latin"] });
const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModelProvider>
            {children}
            <Toaster />
            <SonnarToaster position="bottom-left" />
          </ModelProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
